### ISSUE TITLE
Youtube video question type 

### ISSUE THREAD

**Issue by pfirpfel** [pfirpfel/pub-quiz-generator#4]
Features:
- add new script command that fetches the video/audio and writes it into the media directory
- post-processing to cut down video/audio with start/end attributes

Possible config:
```yaml
questions:
    - type: youtube-dl # question with a video file automatically extracted from youtube
      url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      video: true # default: true
      audio: true # default: true
      start: 0:00 # default: 0:00
      end: 1:00 # default: until the end
      cache-file: media/c1q3.webp # default, generated name
      autoplay: true # default: true
      controls: true # display control buttons (volume, seeking, and pause/resume), default: true
      title: Some title # optional, displayed above video
      caption: A caption # optional, displayed below video
      answer: An answer
      source: https://www.youtube.com/watch?v=dQw4w9WgXcQ # defaults to url
```
